name: Pull Request

on:
  pull_request:
    branches: [main]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  MODEL: "gpt-3.5-turbo"
  TEMPERATURE: 0.7

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node: [16]

    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: git log
      - name: Get latest Git commit SHA and review
        id: review_script
        run: |
          echo "Latest Git commit SHA: $RELEVANT_SHA"
          yarn review $RELEVANT_SHA
        env:
          RELEVANT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Post comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          script: |
            const output = `**Script Output:**\n${{ steps.review_script.outputs.stdout }}`;
            const { data: comments } = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number
            });
            if (comments.length > 0) {
              const commentId = comments[0].id;
              await github.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: commentId,
                body: output
              });
            } else {
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: output
              });
            }


